name: Greeting from Ric
on: push


jobs:
  my-job:
    name: My Job
	  runs-on: ubuntu-latest
	  steps:
	  - name: Print a greeting
	  env:
		  MY_VAR: Hi there! My name is
		  FIRST_NAME: Ric
		  MIDDLE_NAME: Lim
		  LAST_NAME: COO
	  run: |
		  echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
